---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 2024 SCGIS Conference Presentation: Shiny Happy People Sharing Geospatial Data

<!-- badges: start -->
<!-- badges: end -->

Hey there, map enthusiasts and data lovers! 👋🌍📊
Welcome to our GitHub repo for "Shiny Happy People Sharing Geospatial Data" - this presentation was part of the 2024 SCGIS Conference.  

In this presentation, we (@sayersr and @mhegeman) examine some common challenges when visualizing your spatial data and sharing those results with our colleagues. But don't worry, we've got solutions! We introduce you to Shinylive - a web app framework that works with both R and Python. With Shinylive you can create  lightweight, serverless apps that are easy to share.  

We walk you through building an interactive map that can plot your spatial data using Leaflet, all while keeping things private. It's like having your cake and eating it too! 🍰  

We wrap up with a look at the cool benefits of this approach, some challenges to keep in mind, and exciting ideas for future enhancements. So dive in, explore our slides, and let's make sharing geospatial data a breeze! If you have any questions or just want to geek out about maps, give us a shout. Happy mapping! 🗺️✨  


Resources that helped us:  
[Lonboard: Fast, Interactive Geospatial Visualization in Jupyter & JavaScript - Kyle Barron - nyhackr](https://www.youtube.com/live/p3zh85rq6A8?si=dRc5u9REmXB83UYN)  

[Running R-Shiny without a Server - posit::conf(2023)](https://youtu.be/j1M6YyU2ZX8?si=3qX_sW5Kn6DStAZA)  

[How to run Shiny Apps in your browser with WebR (webr.bundle)](https://youtu.be/ZvodHcGsgrU?si=5NPiQt5jUHoUem_d)  

[PyScript Demo / Tutorial | End-to-end PyScript Tutorial #1](https://youtu.be/Qo8dXyKXyME?si=Vu5VZEivUKxtEPDA)  
